# Site settings
title: yyttmonster
SEOTitle: yyttmonster | Blog
header-img: img/home-bg.jpg
email: yyttmonster@outloook.com
description: ""
keyword: ""
url: "http://yyttmonster.cn"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
# weibo_username:     yyttmonster
zhihu_username:     yyttmonster
github_username:    yyttmonster
twitter_username:   yyttmonster
facebook_username:  yyttmonster



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: yyttmonster

# Duoshuo settings
# duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 8df1bed41e5ab2af4adfdbc30e1a9d64
# Google Analytics
ga_track_id: 'UA-173849637-1'            # Format: UA-xxxxxx-xx
ga_domain: yyttmonster.cn



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "You are more than what you have become."
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "linkinpark213",
        href: "http://linkinpark213.com/"
    },{
        title: "hahahawu",
        href: "https://hahahawu.com/"
    },
    {
        title: "Hux Blog",
        href: "http://huangxuan.me"
    }
]
